name: Trigger auto deployment for allsafe-asm-container

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/allsafe-asm-container-AutoDeployTrigger-b3d47bd1-ddd9-4ef5-abe9-efe51808b4b9.yml'

  # Allow manual trigger 
  workflow_dispatch:
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.ALLSAFEASMCONTAINER_AZURE_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          registryUrl: docker.io
          registryUsername: ${{ secrets.ALLSAFEASMCONTAINER_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.ALLSAFEASMCONTAINER_REGISTRY_PASSWORD }}
          containerAppName: allsafe-asm-container
          resourceGroup: ASM
          imageToBuild: hazemusama/hazemusama/api:${{ github.sha }}
          
            

     

