name: Deploy to Azure Container App

env:
  DOCKERHUB_USERNAME: hazemusama
  DOCKERHUB_REPO: api

on:

  workflow_call:
    inputs:
      image_tag:
        description: 'The tag needed to deploy'
        required: true
        type: string

jobs:
  azure:
    runs-on: ubuntu-latest

    steps:

      # 1. Log in to Azure using the Service Principal credentials
      - name: 'Login to Azure'
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # 2. Deploy to Azure Container App using Azure CLI
      - name: 'Deploy to Azure Container App'
        run: |
          az containerapp update \
            --name ${{ secrets.CONTAINER_APP_NAME }} \
            --resource-group ${{ secrets.RESOURCE_GROUP }} \
            --image ${{ env.DOCKERHUB_USERNAME }}/${{ env.DOCKERHUB_REPO }}:${{ inputs.image_tag }} \
            --no-wait
