# This is your main CI file, e.g., .github/workflows/build-and-deploy.yml

name: Build and Deploy Application

on:
  push:
    branches: [ main, master ]
    tags: [ 'v*' ]


env:
  REGISTRY: docker.io
  IMAGE_NAME: hazemusama/api

jobs:
  # --- JOB 1: Build and Push the Docker Image ---
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      
    # ADDED: This 'outputs' block makes the image name available to other jobs
    outputs:
      image_tag: ${{ steps.meta.outputs.version }}
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            # We no longer need the SHA tag if we're not deploying it
            # type=sha,prefix={{branch}}-

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Pass tag to Azure deploy
      - id: azure-tag
        run: echo "tag=${{ steps.meta.outputs.tags }}" >> "$GITHUB_OUTPUT"

  # --- JOB 2: Call the Reusable Deploy Workflow ---
  # CHANGED: 'deploy' is now correctly indented at the same level as 'build-and-push'
  deploy:
    # This job will only run if the 'build-and-push' job completes successfully
    needs: build-and-push
        
    # This 'uses' keyword calls our reusable workflow
    uses: ./.github/workflows/deploy-to-azure.yml # Make sure this filename is correct
    
    # 'with' provides the inputs defined in the reusable workflow
    with:
      # Pass the output from the 'build-and-push' job directly as an input
      # CHANGED: This now correctly references the job output
      tag: ${{ needs.build-and-push.outputs.image_tag }}
      
    # 'secrets: inherit' is the modern, easy way to pass all necessary secrets
    secrets: inherit
